############################ Default configuration #########################
baseURL = "https://nervous-wright-ea05a8.netlify.com/"
languageCode = "en-us"
# site title 
title = "Kevin Bonds | Portfolio"
# theme
theme = "northendlab-hugo"
author = "Kevin Bonds"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "5"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


########################### Navigation ###################################

# main menu
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 2

# [[menu.main]]
# URL = "tools"
# name = "tools"
# weight = 2

[[menu.main]]
URL = "https://github.com/kwbonds?tab=repositories"
name = "Project Repos"
icon = "ti-github"
weight = 3

[[menu.main]]
URL = "resume"
name = "Resumé"
#icon = 'ti-resume'
weight = 1

# footer menu
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 2

# [[menu.footer]]
# URL = "tools"
# name = "tools"
# weight = 2

[[menu.footer]]
URL = "https://github.com/kwbonds?tab=repositories"
name = "Project Repos"
# icon = "ti-github"
weight = 3

[[menu.footer]]
URL = "resume"
name = "Resumé"
#icon = 'ti-resume'
weight = 1

######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/resume.png"
# meta data
author = "Themefisher"
description = "Data Science Portfilio"
# google analitycs ID
googleAnalitycsID = "UA-113458466-2"
# contact form action
contactFormAction = "https://formspree.io/xzbzwkwp" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true


####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = "Hi, I'm Kevin Bonds. I help companies make data-driven decisions"
image = "images/banner/Desk_back.png"
copyright = "&copy; Icons made by [freepik](https://www.flaticon.com/authors/freepik)"


######################## call to action ###############################
# [params.cta]
# enable = true
# image = "images/hugo-muscot.svg"
# title = "Get the best hugo templates"
# description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
# [params.cta.button]
# enable = true
# label = "Visit Here"
# link = "https://gethugothemes.com/shop/"


############################## Social Site ##########################
[[params.social]]
icon = "ti-skype" # themify icon pack https://themify.me/themify-icons
link = "https://join.skype.com/invite/u45PzQhKsLp5"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "https://twitter.com/KevinWBonds"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/kwbonds"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "https://www.linkedin.com/in/kevin-bonds/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
